config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "/images"
  resources :images, only: [:new, :create, :index, :edit, :update]
  default_url_options :host => 'localhost'
  devise_for :travellers, :controllers => {sessions: 'travellers/sessions', :registrations => 'travellers/registrations'}
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  authenticate :traveller do
    resources :travellers, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :admins, only: [:index, :show]

  # devise_scope :admin do
    # authenticated  do
    #   root to: 'admins#index'
    # end

  #   unauthenticated do
  #     root to: 'admins/sessions#new'
  #   end
  # end

  devise_scope :traveller do
    authenticated  do
      root to: 'home#index'
    end

    unauthenticated do
      root to: 'travellers/sessions#new'
    end
  end
  authenticate :admin do
    resources :countries, only: [:new, :create, :edit, :update, :destroy]
    resources :airports, only: [:new, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :travellers
  resources :searches
  resources :countries, :only => [:edit, :create, :show, :update]
  resources :searches do
    member do
      put :update_matches
      get :matches
    end
  end
  resources :airports, :only => [:update]
  resources :airports do
    member do
      put :capital_update
      get :capital_flights
      put :get_flights
      patch :get_flights
    end
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :traveller_countries
  has_many :travellers, through: :traveller_countries
  accepts_nested_attributes_for :travellers
  has_many :airports
  has_many :images, :as => :imageable, dependent: :destroy
  accepts_nested_attributes_for :images

  include HTTParty

  # def self.token=(token)
  #   @token = token
  # end

  # def self.token
  #   @token
  # end

  def self.current_traveller=(traveller)
    @current_traveller = traveller
  end

  def self.current_traveller
    @current_traveller
  end

  def in_budget?(search)
    self.dollars_per_day < search.daily_budget.to_f
    # Country.current_traveller = search.traveller
  end

  def dollars_per_day
    unless self.gdp_ppp.nil?
      percent_diff = ((self.gdp_ppp - 57466.7871132348) / 57466.7871132348 * 100)
      dollars_per_day = (200.00 + percent_diff).round(2) 
    end
  end

  def cost_converter
    results = self.class.get('https://openexchangerates.org/api/latest.json', query: {
      app_id: Search.exchange_rate_token,
    })
    body = JSON.parse(results.body)
    home_country = Country.find(Country.current_traveller.home_location_id)
    # not sure this is right = exhange not touchiing current country choice?
    exchange = body["rates"]["#{home_country.currency_code}"]
    cost_per_day = self.dollars_per_day * exchange
    cost_per_day.round(2)
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  layout 'countries/main', only: [:show]
  def edit
    @country = Country.find(params[:id])
    @image = @country.images.build
  end

  def update
    @country = Country.find(params[:id])
    @country.update(country_params)
    if @country.save
      redirect_to country_path(@country)
    else
      render :edit
    end
  end

  def create
    @country = Country.new(country_params)
    Country.current_traveller = Traveller.find(session_params[:current_traveller])
    @country.save
  end

  def show
    if params[:search]
      @search = Search.find(params[:search])
    end
    @country = Country.find(params[:id])
    @airports = @country.airports.where("municipality is NOT NULL and municipality != ''")
    @capital_flights = @airports.where(iata_code: @country.airport_code)
    @images = @country.images
  end

  private

  def session_params
    params.require(:session).permit(:current_traveller)
  end

  def country_params
    params.require(:country).permit(:name, :iso2, :iso3, :itu, :fips, :currency_code, :currency, :capital, :continent, :gdp_ppp, :content, :images_attributes => [:image])
  end
end

app/views/layouts/countries/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelMatch</title>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome-4.7.0/css/font-awesome.min.css">
  </head>
  <body style='background-image: url("<%= country_profile_image %>"); background-attachment: fixed; background-size: cover;' class="country">
    <header>
      <% if admin_signed_in? %>
        <%= render partial: '/layouts/admins/admin_header' %>
      <% elsif traveller_signed_in? %>
        <%= render partial: '/layouts/home/traveller_header' %>
      <% end %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>