config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "/images"
  resources :images, only: [:new, :create, :index, :edit, :update]
  default_url_options :host => 'localhost'
  devise_for :travellers, :controllers => {sessions: 'travellers/sessions', :registrations => 'travellers/registrations'}
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  authenticate :traveller do
    resources :travellers, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :admins, only: [:index, :show]

  # devise_scope :admin do
    # authenticated  do
    #   root to: 'admins#index'
    # end

  #   unauthenticated do
  #     root to: 'admins/sessions#new'
  #   end
  # end

  devise_scope :traveller do
    authenticated  do
      root to: 'home#index'
    end

    unauthenticated do
      root to: 'travellers/sessions#new'
    end
  end
  authenticate :admin do
    resources :countries, only: [:new, :create, :edit, :update, :destroy]
    resources :airports, only: [:new, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :travellers
  resources :searches
  resources :countries, :only => [:edit, :create, :show, :update]
  resources :searches do
    member do
      put :update_matches
      get :matches
    end
  end
  resources :airports, :only => [:update]
  resources :airports do
    member do
      put :capital_update
      get :capital_flights
      put :get_flights
      patch :get_flights
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if traveller_signed_in?
      @traveller = current_traveller
      @search = @traveller.searches.create
    end
  end

end

app/views/layouts/home/_traveller_header.html.erb
<!DOCTYPE html>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a id="nav-bar-img" class="navbar-brand" href="<%= root_path %>"><img alt="Travel Match" src="/noun_390003_cc.svg" height="50">
        <a class="navbar-brand" href="<%= root_path %>">Travel Match</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= root_path %>">About</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to('Log Out', destroy_traveller_session_path, method: :delete) %></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Profile</li>
            <li><a href="<%= traveller_path(current_traveller) %>">View Profile</a></li>
            <li><a href="<%= edit_traveller_path(current_traveller) %>">Edit Profile</a></li>
          </ul>
       </li>
     </div>
   </div>
 </nav>